PROGRAM = diag
PACKAGE_NAME = diagapp
PACKAGE_DIRS = kos errors io bytes path strings syscall time os path/filepath fmt bufio strconv net net/url net/http ui
ROOT = ../..

include $(ROOT)/mk/kolibri-app.mk
